-- Generated by nwg-displays on 2026-06-11 at 13:36:35. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "1920x1080@60.0",
    position = "3190x1121",
    scale = 1.0
})
hl.monitor({
    output = "HDMI-A-2",
    mode = "3840x2160@30.0",
    position = "5110x1121",
    scale = 1.0
})
