# 1984 light theme by Bertie Blackman, https://github.com/covertbert/iterm2-1984/

foreground #05266E
background #e4e5f5
selection_foreground #19152c
selection_background #ff16b0
color0 #000000
color1 #b30302
color2 #008a00
color3 #a3a000
color4 #005a9c
color5 #f806fa
color6 #00b2be
color7 #feffff
color8 #767676
color9 #d11c1c
color10 #00bd00
color11 #d4d000
color12 #007acc
color13 #f806fa
color14 #00b2be
color15 #feffff

# URL styles
url_color #ff16b0
url_style single

# Cursor styles
cursor #00b2be
